### ISSUE TITLE
Autocomplete URLs entered without protocol

### ISSUE THREAD

**Issue by aarongarciah** [microlinkhq/www#90]
Would be nice to autocomplete the URL entered by the user when no protocol is added. Maybe add _https://_ by default when no protocol is provided by the user?

<img width="1552" alt="screen shot 2018-04-11 at 11 16 32" src="https://user-images.githubusercontent.com/7225802/38607990-6b85bb3e-3d7a-11e8-8e01-f03123414dc5.png">

I think it would improve the user experience and first impression of newcomers.

**Comment by Kikobeats** [comment]
I prefer to force people instead of inferring the protocol; although I'm sure it could work fine for an amount of case, could be a bad user experience if you are supposing the target URL is HTTPS and it doesn't work because actually, it's HTTP.

Also, the `type=url` are saying to you that a URL without protocol is not valid. explicit always win!

**Comment by Kikobeats** [comment]
I'm going to keep the issue open because could be possible make a double request trying HTTPS/HTTP and wait the first request that response using [Promise.Race](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Promise/race). Wanna PR?

**Comment by aarongarciah** [comment]
Yeah, explicit always wins, but it's very probable that if a user enters an URL without protocol it was intended to have one. I'll try to find a time slot this week to do a PR with the https/http feature 😄 

Thanks for being open to new ideas.
